DBZ-7065 Add transform
debezium/debezium-connector-jdbc pull request #45
Opened 2023-10-30 06:32 UTC by rkudryashov

2023-11-05 09:34 UTC, rkudryashov commented
done

2023-11-07 15:51 UTC, rkudryashov commented
@Naros @jpechane

2023-11-08 12:10 UTC, jpechane requested changes
@rkudryashov LGTM, thanks. I left copule of comments related to robustness of the code but from the functional point e are good to go.
Could you please preparea docs for the SMT too?

2023-11-08 12:10 UTC, jpechane commented on src/main/java/io/debezium/connector/jdbc/transform/ConvertCloudEventToSaveableForm.java
> +        if (!record.valueSchema().name().endsWith(CLOUD_EVENTS_SCHEMA_NAME_SUFFIX) || fieldsMapping.isEmpty()) {
```suggestion
        if (record == null || !record.valueSchema().name().endsWith(CLOUD_EVENTS_SCHEMA_NAME_SUFFIX) || fieldsMapping.isEmpty()) {
```
Guard against tombstone messages

2023-11-08 12:10 UTC, jpechane commented on src/main/java/io/debezium/connector/jdbc/transform/ConvertCloudEventToSaveableForm.java
> +            if (rawFieldMapping.contains(FIELD_NAME_SEPARATOR)) {
```suggestion
            if (parts.length > 1) {
```

2023-11-08 15:43 UTC, rkudryashov commented
@jpechane applied suggestions, thanks

I'll create the docs

2023-11-09 06:13 UTC, merged

2023-11-09 06:13 UTC, jpechane commented
@rkudryashov Applied, thanks!